import Head from "next/head";
import Image from "next/image";
import JNSection from "../components/home/JNSection";
import PresidentSection from "../components/home/PresidentSection";
import styles from "../styles/Home.module.css";
import Banner from "../components/Banner";

export default function Home() {
  return (
    <div className="">
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <div className="">
        <Banner imageClass="banner-home" text="" />
        <div className="container w-full flex items-center justify-center">
          <JNSection />
          <div className="divider lg:divider-horizontal"></div>
          <PresidentSection />
        </div>
      </div>
    </div>
  );
}
